### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by spgarbet** [harrelfe/hreport#1]
.Rbuildignore is a symbolic link. This prevents most tools from installing this package. Please remove the symlink.

**Comment by shannongutenkunst** [comment]
I am also interested in this package but cannot install it. I tried installing it using 

> library(githubinstall) 
> githubinstall("hreport")

and I got the following messages:

The downloaded binary packages are in
	/var/folders/cx/d4sy_3y50qd0jly8rfkrbq0h0000gn/T//Rtmp9feLpw/downloaded_packages
✔  checking for file ‘/private/var/folders/cx/d4sy_3y50qd0jly8rfkrbq0h0000gn/T/Rtmp9feLpw/remotes51c772fd8175/harrelfe-hreport-130997a/DESCRIPTION’ (580ms)
   cp: harrelfe-hreport-130997a/.Rbuildignore: No such file or directory
    ERROR
   copying to build directory failed
Error: Failed to install 'hreport' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed
In addition: Warning message:
In fread(download_url, sep = "\t", header = FALSE, stringsAsFactors = FALSE,  :
  Found and resolved improper quoting out-of-sample. First healed line 4848: <<Puriney	honfleuR	"Evening, honfleuR" by Seurat>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.

I also tried installing it using
> library(devtools)
> install_github("harrelfe/hreport")

but I got the following message:

Downloading GitHub repo harrelfe/hreport@HEAD
✔  checking for file ‘/private/var/folders/cx/d4sy_3y50qd0jly8rfkrbq0h0000gn/T/Rtmp9feLpw/remotes51c7295d238c/harrelfe-hreport-130997a/DESCRIPTION’ (355ms)
   cp: harrelfe-hreport-130997a/.Rbuildignore: No such file or directory
    ERROR
   copying to build directory failed
Error: Failed to install 'hreport' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed


Any help installing this package would be greatly appreciated. Thank you for your time.

**Comment by remlapmot** [comment]
You have a few options. 

There are 2 built versions and the source version of the package available on https://hbiostat.org/R/hreport/

<img width="1109" alt="hreport-ss" src="https://user-images.githubusercontent.com/3777473/194537083-c6b105f2-7ec3-43d2-a8ee-5bb1bae67bb2.png">

Hovering the mouse over the *Current source package* text gives the URL of the *.tar.gz* file, which you can use in `install.packages()` in R as follows

```r
install.packages("https://hbiostat.org/R/hreport/hreport_current.tar.gz", repos = NULL, type = "source")
```

**Comment by shannongutenkunst** [comment]
Thanks so much! That worked for me.
