### ISSUE TITLE
Is ssafety dataset used in report.Rmd publicly available?

### ISSUE THREAD

**Issue by shannongutenkunst** [harrelfe/hreport#3]
Hi. I am trying to learn how to use hreport by reproducing the example report at
https://github.com/harrelfe/hreport/tree/master/inst/tests/report.Rmd

However, it looks like I need the ssafety dataset to do that. Is that data publicly available, and if so, where?

Thanks,
Shannon

**Comment by harrelfe** [comment]
```
require(Hmisc)
getHdata(safety). # stores result in data frame named All
```
